spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/KiranaTransactions
    # username: {yourusername}
    # password: {yourpassword}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        web: DEBUG
